# Generated by Django 5.2 on 2025-04-25 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recebedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('org', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('total_pedidos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('org', 'codigo'), name='unique_org_codigo')],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('recebedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.recebedor')),
            ],
        ),
    ]
